Document: brubeck
Title: Debian brubeck Manual
Author: <insert document author here>
Abstract: This manual describes what brubeck is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/brubeck/brubeck.sgml.gz

Format: postscript
Files: /usr/share/doc/brubeck/brubeck.ps.gz

Format: text
Files: /usr/share/doc/brubeck/brubeck.text.gz

Format: HTML
Index: /usr/share/doc/brubeck/html/index.html
Files: /usr/share/doc/brubeck/html/*.html
