#!/bin/sh

set -e
ROOT=$(git rev-parse --show-toplevel)
cd $ROOT

echo "=> Cleaning @ $(date)"
git clean -fdx
git submodule update --init
(cd vendor/ck && git clean -dfx)

echo "=> Testing @ $(date)"
make test

echo "=> Building @ $(date)"
make brubeck
